apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: schedule-pod-in-zone
  annotations:
    pod-policies.kyverno.io/autogen-controllers: Deployment,StatefulSet
spec:
  rules:
  - name: add-node-affinity-for-zone
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
            - CREATE
            - UPDATE
          selector:
                matchExpressions:
                    - {key: app, operator: In, values: [app1,app2]}
      - resources:
          kinds:
          - Pod
          namespaces:
          - prod
          - test-ronak
          operations:
          - CREATE
          - UPDATE

    # exclude:
    #   any:
    #   - resources:
    #       namespaces:
    #       - kube-system
    #   - resources:
    #       kinds:
    #       - Pods
    #       operations:
    #       - CREATE
    #       - UPDATE
    #       namespaceSelector:
    #         matchExpressions:
    #           - key: type 
    #             operator: In
    #             values: 
    #             - connector
    #             - compute
             
    context:
    - name: dictionary
      configMap:
        name: az-availability
        namespace: default
    mutate:
      patchStrategicMerge:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - "{{dictionary.data.zone}}"
